/*
 * Selling Partner API for Product Fees
 *
 * The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FeesEstimateByIdRequest : A product, marketplace, and proposed price used to request estimated fees.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FeesEstimateByIdRequest {
    #[serde(rename = "FeesEstimateRequest", skip_serializing_if = "Option::is_none")]
    pub fees_estimate_request: Option<Box<crate::models::FeesEstimateRequest>>,
    #[serde(rename = "IdType")]
    pub id_type: crate::models::IdType,
    /// The item identifier.
    #[serde(rename = "IdValue")]
    pub id_value: String,
}

impl FeesEstimateByIdRequest {
    /// A product, marketplace, and proposed price used to request estimated fees.
    pub fn new(id_type: crate::models::IdType, id_value: String) -> FeesEstimateByIdRequest {
        FeesEstimateByIdRequest {
            fees_estimate_request: None,
            id_type,
            id_value,
        }
    }
}


