/*
 * Selling Partner API for Easy Ship
 *
 * The Selling Partner API for Easy Ship helps you build applications that help sellers manage and ship Amazon Easy Ship orders.  Your Easy Ship applications can:  * Get available time slots for packages to be scheduled for delivery.  * Schedule, reschedule, and cancel Easy Ship orders.  * Print labels, invoices, and warranties.  See the [Marketplace Support Table](doc:easy-ship-api-v2022-03-23-use-case-guide) for the differences in Easy Ship operations by marketplace.
 *
 * The version of the OpenAPI document: 2022-03-23
 * Contact: marketplaceapitest@amazon.com
 * Generated by: https://openapi-generator.tech
 */

/// ScheduledPackageId : Identifies the scheduled package to be updated.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScheduledPackageId {
    /// An Amazon-defined order identifier. Identifies the order that the seller wants to deliver using Amazon Easy Ship.
    #[serde(rename = "amazonOrderId")]
    pub amazon_order_id: String,
    /// An Amazon-defined identifier for the scheduled package.
    #[serde(rename = "packageId", skip_serializing_if = "Option::is_none")]
    pub package_id: Option<String>,
}

impl ScheduledPackageId {
    /// Identifies the scheduled package to be updated.
    pub fn new(amazon_order_id: String) -> ScheduledPackageId {
        ScheduledPackageId {
            amazon_order_id,
            package_id: None,
        }
    }
}


