/*
 * Selling Partner API for Easy Ship
 *
 * The Selling Partner API for Easy Ship helps you build applications that help sellers manage and ship Amazon Easy Ship orders.  Your Easy Ship applications can:  * Get available time slots for packages to be scheduled for delivery.  * Schedule, reschedule, and cancel Easy Ship orders.  * Print labels, invoices, and warranties.  See the [Marketplace Support Table](doc:easy-ship-api-v2022-03-23-use-case-guide) for the differences in Easy Ship operations by marketplace.
 *
 * The version of the OpenAPI document: 2022-03-23
 * Contact: marketplaceapitest@amazon.com
 * Generated by: https://openapi-generator.tech
 */

/// UnitOfWeight : The unit of measurement used to measure the weight.

/// The unit of measurement used to measure the weight.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UnitOfWeight {
    #[serde(rename = "Grams")]
    Grams,
    #[serde(rename = "G")]
    G,

}

impl ToString for UnitOfWeight {
    fn to_string(&self) -> String {
        match self {
            Self::Grams => String::from("Grams"),
            Self::G => String::from("G"),
        }
    }
}

impl Default for UnitOfWeight {
    fn default() -> UnitOfWeight {
        Self::Grams
    }
}




