/*
 * Selling Partner API for Easy Ship
 *
 * The Selling Partner API for Easy Ship helps you build applications that help sellers manage and ship Amazon Easy Ship orders.  Your Easy Ship applications can:  * Get available time slots for packages to be scheduled for delivery.  * Schedule, reschedule, and cancel Easy Ship orders.  * Print labels, invoices, and warranties.  See the [Marketplace Support Table](doc:easy-ship-api-v2022-03-23-use-case-guide) for the differences in Easy Ship operations by marketplace.
 *
 * The version of the OpenAPI document: 2022-03-23
 * Contact: marketplaceapitest@amazon.com
 * Generated by: https://openapi-generator.tech
 */

/// UpdateScheduledPackagesRequest : The request schema for the `updateScheduledPackages` operation.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateScheduledPackagesRequest {
    /// A string of up to 255 characters.
    #[serde(rename = "marketplaceId")]
    pub marketplace_id: String,
    /// A list of package update details.
    #[serde(rename = "updatePackageDetailsList")]
    pub update_package_details_list: Vec<crate::models::UpdatePackageDetails>,
}

impl UpdateScheduledPackagesRequest {
    /// The request schema for the `updateScheduledPackages` operation.
    pub fn new(marketplace_id: String, update_package_details_list: Vec<crate::models::UpdatePackageDetails>) -> UpdateScheduledPackagesRequest {
        UpdateScheduledPackagesRequest {
            marketplace_id,
            update_package_details_list,
        }
    }
}


