/*
 * Selling Partner API for Product Type Definitions
 *
 * The Selling Partner API for Product Type Definitions provides programmatic access to attribute and data requirements for product types in the Amazon catalog. Use this API to return the JSON Schema for a product type that you can then use with other Selling Partner APIs, such as the Selling Partner API for Listings Items, the Selling Partner API for Catalog Items, and the Selling Partner API for Feeds (for JSON-based listing feeds).  For more information, see the [Product Type Definitions API Use Case Guide](doc:product-type-api-use-case-guide).
 *
 * The version of the OpenAPI document: 2020-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SchemaLinkLink : Link to retrieve the schema.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SchemaLinkLink {
    /// URI resource for the link.
    #[serde(rename = "resource")]
    pub resource: String,
    /// HTTP method for the link operation.
    #[serde(rename = "verb")]
    pub verb: Verb,
}

impl SchemaLinkLink {
    /// Link to retrieve the schema.
    pub fn new(resource: String, verb: Verb) -> SchemaLinkLink {
        SchemaLinkLink {
            resource,
            verb,
        }
    }
}

/// HTTP method for the link operation.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Verb {
    #[serde(rename = "GET")]
    GET,
}

impl Default for Verb {
    fn default() -> Verb {
        Self::GET
    }
}

