/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Dimension : Individual dimension value of an Amazon catalog item or item package.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dimension {
    /// Measurement unit of the dimension value.
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    /// Numeric dimension value.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<f32>,
}

impl Dimension {
    /// Individual dimension value of an Amazon catalog item or item package.
    pub fn new() -> Dimension {
        Dimension {
            unit: None,
            value: None,
        }
    }
}


