/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Dimensions : Dimensions of an Amazon catalog item or item in its packaging.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Dimensions {
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<Box<crate::models::Dimension>>,
    #[serde(rename = "length", skip_serializing_if = "Option::is_none")]
    pub length: Option<Box<crate::models::Dimension>>,
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<Box<crate::models::Dimension>>,
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<Box<crate::models::Dimension>>,
}

impl Dimensions {
    /// Dimensions of an Amazon catalog item or item in its packaging.
    pub fn new() -> Dimensions {
        Dimensions {
            height: None,
            length: None,
            weight: None,
            width: None,
        }
    }
}


