/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ItemIdentifiersByMarketplace : Identifiers associated with the item in the Amazon catalog for the indicated Amazon marketplace.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ItemIdentifiersByMarketplace {
    /// Amazon marketplace identifier.
    #[serde(rename = "marketplaceId")]
    pub marketplace_id: String,
    /// Identifiers associated with the item in the Amazon catalog for the indicated Amazon marketplace.
    #[serde(rename = "identifiers")]
    pub identifiers: Vec<crate::models::ItemIdentifier>,
}

impl ItemIdentifiersByMarketplace {
    /// Identifiers associated with the item in the Amazon catalog for the indicated Amazon marketplace.
    pub fn new(marketplace_id: String, identifiers: Vec<crate::models::ItemIdentifier>) -> ItemIdentifiersByMarketplace {
        ItemIdentifiersByMarketplace {
            marketplace_id,
            identifiers,
        }
    }
}


