/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ItemVendorDetailsCategory : Product category or subcategory associated with an Amazon catalog item.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ItemVendorDetailsCategory {
    /// Display name of the product category or subcategory
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Value (code) of the product category or subcategory.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl ItemVendorDetailsCategory {
    /// Product category or subcategory associated with an Amazon catalog item.
    pub fn new() -> ItemVendorDetailsCategory {
        ItemVendorDetailsCategory {
            display_name: None,
            value: None,
        }
    }
}


