/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ItemVariationTheme : Variation theme indicating the combination of Amazon item catalog attributes that define the variation family.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ItemVariationTheme {
    /// Names of the Amazon catalog item attributes associated with the variation theme.
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<String>>,
    /// Variation theme indicating the combination of Amazon item catalog attributes that define the variation family.
    #[serde(rename = "theme", skip_serializing_if = "Option::is_none")]
    pub theme: Option<String>,
}

impl ItemVariationTheme {
    /// Variation theme indicating the combination of Amazon item catalog attributes that define the variation family.
    pub fn new() -> ItemVariationTheme {
        ItemVariationTheme {
            attributes: None,
            theme: None,
        }
    }
}


