/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ItemBrowseClassification : Classification (browse node) associated with an Amazon catalog item.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ItemBrowseClassification {
    /// Display name for the classification.
    #[serde(rename = "displayName")]
    pub display_name: String,
    /// Identifier of the classification (browse node identifier).
    #[serde(rename = "classificationId")]
    pub classification_id: String,
}

impl ItemBrowseClassification {
    /// Classification (browse node) associated with an Amazon catalog item.
    pub fn new(display_name: String, classification_id: String) -> ItemBrowseClassification {
        ItemBrowseClassification {
            display_name,
            classification_id,
        }
    }
}


