/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ItemIdentifier : Identifier associated with the item in the Amazon catalog, such as a UPC or EAN identifier.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ItemIdentifier {
    /// Type of identifier, such as UPC, EAN, or ISBN.
    #[serde(rename = "identifierType")]
    pub identifier_type: String,
    /// Identifier.
    #[serde(rename = "identifier")]
    pub identifier: String,
}

impl ItemIdentifier {
    /// Identifier associated with the item in the Amazon catalog, such as a UPC or EAN identifier.
    pub fn new(identifier_type: String, identifier: String) -> ItemIdentifier {
        ItemIdentifier {
            identifier_type,
            identifier,
        }
    }
}


