/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ItemImage : Image for an item in the Amazon catalog.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ItemImage {
    /// Variant of the image, such as `MAIN` or `PT01`.
    #[serde(rename = "variant")]
    pub variant: Variant,
    /// Link, or URL, for the image.
    #[serde(rename = "link")]
    pub link: String,
    /// Height of the image in pixels.
    #[serde(rename = "height")]
    pub height: i32,
    /// Width of the image in pixels.
    #[serde(rename = "width")]
    pub width: i32,
}

impl ItemImage {
    /// Image for an item in the Amazon catalog.
    pub fn new(variant: Variant, link: String, height: i32, width: i32) -> ItemImage {
        ItemImage {
            variant,
            link,
            height,
            width,
        }
    }
}

/// Variant of the image, such as `MAIN` or `PT01`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Variant {
    #[serde(rename = "MAIN")]
    MAIN,
    #[serde(rename = "PT01")]
    PT01,
    #[serde(rename = "PT02")]
    PT02,
    #[serde(rename = "PT03")]
    PT03,
    #[serde(rename = "PT04")]
    PT04,
    #[serde(rename = "PT05")]
    PT05,
    #[serde(rename = "PT06")]
    PT06,
    #[serde(rename = "PT07")]
    PT07,
    #[serde(rename = "PT08")]
    PT08,
    #[serde(rename = "SWCH")]
    SWCH,
}

impl Default for Variant {
    fn default() -> Variant {
        Self::MAIN
    }
}

