/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ItemRelationshipsByMarketplace : Relationship details for the Amazon catalog item for the indicated Amazon marketplace.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ItemRelationshipsByMarketplace {
    /// Amazon marketplace identifier.
    #[serde(rename = "marketplaceId")]
    pub marketplace_id: String,
    /// Relationships for the item.
    #[serde(rename = "relationships")]
    pub relationships: Vec<crate::models::ItemRelationship>,
}

impl ItemRelationshipsByMarketplace {
    /// Relationship details for the Amazon catalog item for the indicated Amazon marketplace.
    pub fn new(marketplace_id: String, relationships: Vec<crate::models::ItemRelationship>) -> ItemRelationshipsByMarketplace {
        ItemRelationshipsByMarketplace {
            marketplace_id,
            relationships,
        }
    }
}


