/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Amount : The monetary value.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Amount {
    #[serde(rename = "CurrencyCode")]
    pub currency_code: crate::models::CurrencyCode,
    #[serde(rename = "Value")]
    pub value: f64,
}

impl Amount {
    /// The monetary value.
    pub fn new(currency_code: crate::models::CurrencyCode, value: f64) -> Amount {
        Amount {
            currency_code,
            value,
        }
    }
}


