/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// InboundShipmentPlanRequestItem : Item information for creating an inbound shipment plan. Submitted with a call to the createInboundShipmentPlan operation.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InboundShipmentPlanRequestItem {
    /// The seller SKU of the item.
    #[serde(rename = "SellerSKU")]
    pub seller_sku: String,
    /// The Amazon Standard Identification Number (ASIN) of the item.
    #[serde(rename = "ASIN")]
    pub ASIN: String,
    #[serde(rename = "Condition")]
    pub condition: crate::models::Condition,
    /// The item quantity.
    #[serde(rename = "Quantity")]
    pub quantity: i32,
    /// The item quantity.
    #[serde(rename = "QuantityInCase", skip_serializing_if = "Option::is_none")]
    pub quantity_in_case: Option<i32>,
    /// A list of preparation instructions and who is responsible for that preparation.
    #[serde(rename = "PrepDetailsList", skip_serializing_if = "Option::is_none")]
    pub prep_details_list: Option<Vec<crate::models::PrepDetails>>,
}

impl InboundShipmentPlanRequestItem {
    /// Item information for creating an inbound shipment plan. Submitted with a call to the createInboundShipmentPlan operation.
    pub fn new(seller_sku: String, ASIN: String, condition: crate::models::Condition, quantity: i32) -> InboundShipmentPlanRequestItem {
        InboundShipmentPlanRequestItem {
            seller_sku,
            ASIN,
            condition,
            quantity,
            quantity_in_case: None,
            prep_details_list: None,
        }
    }
}


