/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NonPartneredSmallParcelPackageOutput : Carrier, tracking number, and status information for the package.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NonPartneredSmallParcelPackageOutput {
    /// The carrier that you are using for the inbound shipment.
    #[serde(rename = "CarrierName")]
    pub carrier_name: String,
    /// The tracking number of the package, provided by the carrier.
    #[serde(rename = "TrackingId")]
    pub tracking_id: String,
    #[serde(rename = "PackageStatus")]
    pub package_status: crate::models::PackageStatus,
}

impl NonPartneredSmallParcelPackageOutput {
    /// Carrier, tracking number, and status information for the package.
    pub fn new(carrier_name: String, tracking_id: String, package_status: crate::models::PackageStatus) -> NonPartneredSmallParcelPackageOutput {
        NonPartneredSmallParcelPackageOutput {
            carrier_name,
            tracking_id,
            package_status,
        }
    }
}


