/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PrepGuidance : Item preparation instructions.

/// Item preparation instructions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PrepGuidance {
    #[serde(rename = "ConsultHelpDocuments")]
    ConsultHelpDocuments,
    #[serde(rename = "NoAdditionalPrepRequired")]
    NoAdditionalPrepRequired,
    #[serde(rename = "SeePrepInstructionsList")]
    SeePrepInstructionsList,

}

impl ToString for PrepGuidance {
    fn to_string(&self) -> String {
        match self {
            Self::ConsultHelpDocuments => String::from("ConsultHelpDocuments"),
            Self::NoAdditionalPrepRequired => String::from("NoAdditionalPrepRequired"),
            Self::SeePrepInstructionsList => String::from("SeePrepInstructionsList"),
        }
    }
}

impl Default for PrepGuidance {
    fn default() -> PrepGuidance {
        Self::ConsultHelpDocuments
    }
}




