/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PrepOwner : Indicates who will prepare the item.

/// Indicates who will prepare the item.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PrepOwner {
    #[serde(rename = "AMAZON")]
    AMAZON,
    #[serde(rename = "SELLER")]
    SELLER,

}

impl ToString for PrepOwner {
    fn to_string(&self) -> String {
        match self {
            Self::AMAZON => String::from("AMAZON"),
            Self::SELLER => String::from("SELLER"),
        }
    }
}

impl Default for PrepOwner {
    fn default() -> PrepOwner {
        Self::AMAZON
    }
}




