[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3.11"
dotenv = "0.15.0"
regex = "1"
once_cell = "1"