/*
 * Selling Partner API for Reports
 *
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * The version of the OpenAPI document: 2020-09-04
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CancelReportScheduleResponse : The response for the cancelReportSchedule operation.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CancelReportScheduleResponse {
    /// A list of error responses returned when a request is unsuccessful.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::Error>>,
}

impl CancelReportScheduleResponse {
    /// The response for the cancelReportSchedule operation.
    pub fn new() -> CancelReportScheduleResponse {
        CancelReportScheduleResponse {
            errors: None,
        }
    }
}


