/*
 * Selling Partner API for Reports
 *
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * The version of the OpenAPI document: 2021-06-30
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateReportResponse : Response schema.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateReportResponse {
    /// The identifier for the report. This identifier is unique only in combination with a seller ID.
    #[serde(rename = "reportId")]
    pub report_id: String,
}

impl CreateReportResponse {
    /// Response schema.
    pub fn new(report_id: String) -> CreateReportResponse {
        CreateReportResponse {
            report_id,
        }
    }
}


