/*
 * Selling Partner API for Reports
 *
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * The version of the OpenAPI document: 2021-06-30
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ReportDocument : Information required for the report document.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReportDocument {
    /// The identifier for the report document. This identifier is unique only in combination with a seller ID.
    #[serde(rename = "reportDocumentId")]
    pub report_document_id: String,
    /// A presigned URL for the report document. This URL expires after 5 minutes.
    #[serde(rename = "url")]
    pub url: String,
    /// If present, the report document contents have been compressed with the provided algorithm.
    #[serde(rename = "compressionAlgorithm", skip_serializing_if = "Option::is_none")]
    pub compression_algorithm: Option<CompressionAlgorithm>,
}

impl ReportDocument {
    /// Information required for the report document.
    pub fn new(report_document_id: String, url: String) -> ReportDocument {
        ReportDocument {
            report_document_id,
            url,
            compression_algorithm: None,
        }
    }
}

/// If present, the report document contents have been compressed with the provided algorithm.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CompressionAlgorithm {
    #[serde(rename = "GZIP")]
    GZIP,
}

impl Default for CompressionAlgorithm {
    fn default() -> CompressionAlgorithm {
        Self::GZIP
    }
}

