/*
 * Selling Partner API for Reports
 *
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * The version of the OpenAPI document: 2021-06-30
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ReportScheduleList : A list of report schedules.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReportScheduleList {
    #[serde(rename = "reportSchedules")]
    pub report_schedules: Vec<crate::models::ReportSchedule>,
}

impl ReportScheduleList {
    /// A list of report schedules.
    pub fn new(report_schedules: Vec<crate::models::ReportSchedule>) -> ReportScheduleList {
        ReportScheduleList {
            report_schedules,
        }
    }
}


