/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JobListing : The payload for the GetJobs operation.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JobListing {
    /// Total result size of the query result.
    #[serde(rename = "totalResultSize", skip_serializing_if = "Option::is_none")]
    pub total_result_size: Option<i32>,
    /// A generated string used to pass information to your next request.If nextPageToken is returned, pass the value of nextPageToken to the pageToken to get next results.
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    /// A generated string used to pass information to your next request.If previousPageToken is returned, pass the value of previousPageToken to the pageToken to get previous page results.
    #[serde(rename = "previousPageToken", skip_serializing_if = "Option::is_none")]
    pub previous_page_token: Option<String>,
    /// List of job details for the given input.
    #[serde(rename = "jobs", skip_serializing_if = "Option::is_none")]
    pub jobs: Option<Vec<crate::models::ServiceJob>>,
}

impl JobListing {
    /// The payload for the GetJobs operation.
    pub fn new() -> JobListing {
        JobListing {
            total_result_size: None,
            next_page_token: None,
            previous_page_token: None,
            jobs: None,
        }
    }
}


