/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Seller : Information about the seller of the service job.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Seller {
    /// The identifier of the seller of the service job.
    #[serde(rename = "sellerId", skip_serializing_if = "Option::is_none")]
    pub seller_id: Option<String>,
}

impl Seller {
    /// Information about the seller of the service job.
    pub fn new() -> Seller {
        Seller {
            seller_id: None,
        }
    }
}


