/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Warning : Warning returned when the request is successful but execution have some important callouts on basis of which API clients should take defined actions.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Warning {
    /// An warning code that identifies the type of warning that occurred.
    #[serde(rename = "code")]
    pub code: String,
    /// A message that describes the warning condition in a human-readable form.
    #[serde(rename = "message")]
    pub message: String,
    /// Additional details that can help the caller understand or address the warning.
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
}

impl Warning {
    /// Warning returned when the request is successful but execution have some important callouts on basis of which API clients should take defined actions.
    pub fn new(code: String, message: String) -> Warning {
        Warning {
            code,
            message,
            details: None,
        }
    }
}


