/*
 * Selling Partner API for Direct Fulfillment Orders
 *
 * The Selling Partner API for Direct Fulfillment Orders provides programmatic access to a direct fulfillment vendor's order data.
 *
 * The version of the OpenAPI document: 2021-12-28
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GiftDetails : Gift details for the item.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GiftDetails {
    /// Gift message to be printed in shipment.
    #[serde(rename = "giftMessage", skip_serializing_if = "Option::is_none")]
    pub gift_message: Option<String>,
    /// Gift wrap identifier for the gift wrapping, if any.
    #[serde(rename = "giftWrapId", skip_serializing_if = "Option::is_none")]
    pub gift_wrap_id: Option<String>,
}

impl GiftDetails {
    /// Gift details for the item.
    pub fn new() -> GiftDetails {
        GiftDetails {
            gift_message: None,
            gift_wrap_id: None,
        }
    }
}


