/*
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// HazmatType : Hazardous materials options for a package. Consult the terms and conditions for each carrier for more information on hazardous materials.

/// Hazardous materials options for a package. Consult the terms and conditions for each carrier for more information on hazardous materials.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HazmatType {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "LQHazmat")]
    LQHazmat,

}

impl ToString for HazmatType {
    fn to_string(&self) -> String {
        match self {
            Self::None => String::from("None"),
            Self::LQHazmat => String::from("LQHazmat"),
        }
    }
}

impl Default for HazmatType {
    fn default() -> HazmatType {
        Self::None
    }
}




