/*
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Label : Data for creating a shipping label and dimensions for printing the label.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Label {
    /// Custom text to print on the label.  Note: Custom text is only included on labels that are in ZPL format (ZPL203). FedEx does not support CustomTextForLabel.
    #[serde(rename = "CustomTextForLabel", skip_serializing_if = "Option::is_none")]
    pub custom_text_for_label: Option<String>,
    #[serde(rename = "Dimensions")]
    pub dimensions: Box<crate::models::LabelDimensions>,
    #[serde(rename = "FileContents")]
    pub file_contents: Box<crate::models::FileContents>,
    #[serde(rename = "LabelFormat", skip_serializing_if = "Option::is_none")]
    pub label_format: Option<crate::models::LabelFormat>,
    #[serde(rename = "StandardIdForLabel", skip_serializing_if = "Option::is_none")]
    pub standard_id_for_label: Option<crate::models::StandardIdForLabel>,
}

impl Label {
    /// Data for creating a shipping label and dimensions for printing the label.
    pub fn new(dimensions: crate::models::LabelDimensions, file_contents: crate::models::FileContents) -> Label {
        Label {
            custom_text_for_label: None,
            dimensions: Box::new(dimensions),
            file_contents: Box::new(file_contents),
            label_format: None,
            standard_id_for_label: None,
        }
    }
}


