/*
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Length : The length.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Length {
    /// The value in units.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<f32>,
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<crate::models::UnitOfLength>,
}

impl Length {
    /// The length.
    pub fn new() -> Length {
        Length {
            value: None,
            unit: None,
        }
    }
}


