/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * The version of the OpenAPI document: 2021-12-28
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetShippingLabelResponse : The response schema for the getShippingLabel operation.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetShippingLabelResponse {
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<Box<crate::models::ShippingLabel>>,
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Box<crate::models::ErrorList>>,
}

impl GetShippingLabelResponse {
    /// The response schema for the getShippingLabel operation.
    pub fn new() -> GetShippingLabelResponse {
        GetShippingLabelResponse {
            payload: None,
            errors: None,
        }
    }
}


