/*
 * Selling Partner API for A+ Content Management
 *
 * With the A+ Content API, you can build applications that help selling partners add rich marketing content to their Amazon product detail pages. A+ content helps selling partners share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners assemble content by choosing from content modules and adding images and text.
 *
 * The version of the OpenAPI document: 2020-11-01
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ColorType : The relative color scheme of content.

/// The relative color scheme of content.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ColorType {
    #[serde(rename = "DARK")]
    DARK,
    #[serde(rename = "LIGHT")]
    LIGHT,

}

impl ToString for ColorType {
    fn to_string(&self) -> String {
        match self {
            Self::DARK => String::from("DARK"),
            Self::LIGHT => String::from("LIGHT"),
        }
    }
}

impl Default for ColorType {
    fn default() -> ColorType {
        Self::DARK
    }
}




