/*
 * Selling Partner API for A+ Content Management
 *
 * With the A+ Content API, you can build applications that help selling partners add rich marketing content to their Amazon product detail pages. A+ content helps selling partners share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners assemble content by choosing from content modules and adding images and text.
 *
 * The version of the OpenAPI document: 2020-11-01
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SearchContentPublishRecordsResponseAllOf {
    /// A list of A+ Content publishing records.
    #[serde(rename = "publishRecordList")]
    pub publish_record_list: Vec<crate::models::PublishRecord>,
}

impl SearchContentPublishRecordsResponseAllOf {
    pub fn new(publish_record_list: Vec<crate::models::PublishRecord>) -> SearchContentPublishRecordsResponseAllOf {
        SearchContentPublishRecordsResponseAllOf {
            publish_record_list,
        }
    }
}


