/*
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BuyerRequestedCancel : Information about whether or not a buyer requested cancellation.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BuyerRequestedCancel {
    /// When true, the buyer has requested cancellation.
    #[serde(rename = "IsBuyerRequestedCancel", skip_serializing_if = "Option::is_none")]
    pub is_buyer_requested_cancel: Option<bool>,
    /// The reason that the buyer requested cancellation.
    #[serde(rename = "BuyerCancelReason", skip_serializing_if = "Option::is_none")]
    pub buyer_cancel_reason: Option<String>,
}

impl BuyerRequestedCancel {
    /// Information about whether or not a buyer requested cancellation.
    pub fn new() -> BuyerRequestedCancel {
        BuyerRequestedCancel {
            is_buyer_requested_cancel: None,
            buyer_cancel_reason: None,
        }
    }
}


