/*
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BuyerTaxInformation : Contains the business invoice tax information. Available only in the TR marketplace.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BuyerTaxInformation {
    /// Business buyer's company legal name.
    #[serde(rename = "BuyerLegalCompanyName", skip_serializing_if = "Option::is_none")]
    pub buyer_legal_company_name: Option<String>,
    /// Business buyer's address.
    #[serde(rename = "BuyerBusinessAddress", skip_serializing_if = "Option::is_none")]
    pub buyer_business_address: Option<String>,
    /// Business buyer's tax registration ID.
    #[serde(rename = "BuyerTaxRegistrationId", skip_serializing_if = "Option::is_none")]
    pub buyer_tax_registration_id: Option<String>,
    /// Business buyer's tax office.
    #[serde(rename = "BuyerTaxOffice", skip_serializing_if = "Option::is_none")]
    pub buyer_tax_office: Option<String>,
}

impl BuyerTaxInformation {
    /// Contains the business invoice tax information. Available only in the TR marketplace.
    pub fn new() -> BuyerTaxInformation {
        BuyerTaxInformation {
            buyer_legal_company_name: None,
            buyer_business_address: None,
            buyer_tax_registration_id: None,
            buyer_tax_office: None,
        }
    }
}


