/*
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrderItemsInner {
    /// the unique identifier for the order item
    #[serde(rename = "orderItemId", skip_serializing_if = "Option::is_none")]
    pub order_item_id: Option<String>,
    /// the quantity of items that needs an update of the shipment status
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<i32>,
}

impl OrderItemsInner {
    pub fn new() -> OrderItemsInner {
        OrderItemsInner {
            order_item_id: None,
            quantity: None,
        }
    }
}


