/*
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UpdateVerificationStatusRequest : Request to update the verification status of an order containing regulated products.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateVerificationStatusRequest {
    #[serde(rename = "regulatedOrderVerificationStatus")]
    pub regulated_order_verification_status: Box<crate::models::UpdateVerificationStatusRequestBody>,
}

impl UpdateVerificationStatusRequest {
    /// Request to update the verification status of an order containing regulated products.
    pub fn new(regulated_order_verification_status: crate::models::UpdateVerificationStatusRequestBody) -> UpdateVerificationStatusRequest {
        UpdateVerificationStatusRequest {
            regulated_order_verification_status: Box::new(regulated_order_verification_status),
        }
    }
}


