/*
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UpdateShipmentStatusRequest : Request to update the status of shipment of an order.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateShipmentStatusRequest {
    /// the unobfuscated marketplace ID
    #[serde(rename = "marketplaceId")]
    pub marketplace_id: String,
    #[serde(rename = "shipmentStatus")]
    pub shipment_status: crate::models::ShipmentStatus,
    /// the list of order items and quantities when the seller wants to partially update the shipment status of the order
    #[serde(rename = "orderItems", skip_serializing_if = "Option::is_none")]
    pub order_items: Option<Vec<crate::models::OrderItemsInner>>,
}

impl UpdateShipmentStatusRequest {
    /// Request to update the status of shipment of an order.
    pub fn new(marketplace_id: String, shipment_status: crate::models::ShipmentStatus) -> UpdateShipmentStatusRequest {
        UpdateShipmentStatusRequest {
            marketplace_id,
            shipment_status,
            order_items: None,
        }
    }
}


