/*
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Account : The account related data.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Account {
    /// This is the Amazon Shipping account id generated during the Amazon Shipping onboarding process.
    #[serde(rename = "accountId")]
    pub account_id: String,
}

impl Account {
    /// The account related data.
    pub fn new(account_id: String) -> Account {
        Account {
            account_id,
        }
    }
}


