/*
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CancelShipmentResponse : The response schema for the cancelShipment operation.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CancelShipmentResponse {
    /// A list of error responses returned when a request is unsuccessful.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::Error>>,
}

impl CancelShipmentResponse {
    /// The response schema for the cancelShipment operation.
    pub fn new() -> CancelShipmentResponse {
        CancelShipmentResponse {
            errors: None,
        }
    }
}


