/*
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ContainerItem : Item in the container.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContainerItem {
    /// The quantity of the items of this type in the container.
    #[serde(rename = "quantity")]
    pub quantity: f32,
    #[serde(rename = "unitPrice")]
    pub unit_price: Box<crate::models::Currency>,
    #[serde(rename = "unitWeight")]
    pub unit_weight: Box<crate::models::Weight>,
    /// A descriptive title of the item.
    #[serde(rename = "title")]
    pub title: String,
}

impl ContainerItem {
    /// Item in the container.
    pub fn new(quantity: f32, unit_price: crate::models::Currency, unit_weight: crate::models::Weight, title: String) -> ContainerItem {
        ContainerItem {
            quantity,
            unit_price: Box::new(unit_price),
            unit_weight: Box::new(unit_weight),
            title,
        }
    }
}


