/*
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ContainerSpecification : Container specification for checking the service rate.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContainerSpecification {
    #[serde(rename = "dimensions")]
    pub dimensions: Box<crate::models::Dimensions>,
    #[serde(rename = "weight")]
    pub weight: Box<crate::models::Weight>,
}

impl ContainerSpecification {
    /// Container specification for checking the service rate.
    pub fn new(dimensions: crate::models::Dimensions, weight: crate::models::Weight) -> ContainerSpecification {
        ContainerSpecification {
            dimensions: Box::new(dimensions),
            weight: Box::new(weight),
        }
    }
}


