/*
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateShipmentRequest : The request schema for the createShipment operation.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateShipmentRequest {
    /// Client reference id.
    #[serde(rename = "clientReferenceId")]
    pub client_reference_id: String,
    #[serde(rename = "shipTo")]
    pub ship_to: Box<crate::models::Address>,
    #[serde(rename = "shipFrom")]
    pub ship_from: Box<crate::models::Address>,
    /// A list of container.
    #[serde(rename = "containers")]
    pub containers: Vec<crate::models::Container>,
}

impl CreateShipmentRequest {
    /// The request schema for the createShipment operation.
    pub fn new(client_reference_id: String, ship_to: crate::models::Address, ship_from: crate::models::Address, containers: Vec<crate::models::Container>) -> CreateShipmentRequest {
        CreateShipmentRequest {
            client_reference_id,
            ship_to: Box::new(ship_to),
            ship_from: Box::new(ship_from),
            containers,
        }
    }
}


