/*
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Currency : The total value of all items in the container.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Currency {
    /// The amount of currency.
    #[serde(rename = "value")]
    pub value: f32,
    /// A 3-character currency code.
    #[serde(rename = "unit")]
    pub unit: String,
}

impl Currency {
    /// The total value of all items in the container.
    pub fn new(value: f32, unit: String) -> Currency {
        Currency {
            value,
            unit,
        }
    }
}


