/*
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Party : The account related with the shipment.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Party {
    /// This is the Amazon Shipping account id generated during the Amazon Shipping onboarding process.
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
}

impl Party {
    /// The account related with the shipment.
    pub fn new() -> Party {
        Party {
            account_id: None,
        }
    }
}


