/*
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PurchaseLabelsRequest : The request schema for the purchaseLabels operation.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PurchaseLabelsRequest {
    /// An identifier for the rating.
    #[serde(rename = "rateId")]
    pub rate_id: String,
    #[serde(rename = "labelSpecification")]
    pub label_specification: Box<crate::models::LabelSpecification>,
}

impl PurchaseLabelsRequest {
    /// The request schema for the purchaseLabels operation.
    pub fn new(rate_id: String, label_specification: crate::models::LabelSpecification) -> PurchaseLabelsRequest {
        PurchaseLabelsRequest {
            rate_id,
            label_specification: Box::new(label_specification),
        }
    }
}


