/*
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PurchaseShipmentRequest : The payload schema for the purchaseShipment operation.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PurchaseShipmentRequest {
    /// Client reference id.
    #[serde(rename = "clientReferenceId")]
    pub client_reference_id: String,
    #[serde(rename = "shipTo")]
    pub ship_to: Box<crate::models::Address>,
    #[serde(rename = "shipFrom")]
    pub ship_from: Box<crate::models::Address>,
    /// The start date and time. This defaults to the current date and time.
    #[serde(rename = "shipDate", skip_serializing_if = "Option::is_none")]
    pub ship_date: Option<String>,
    #[serde(rename = "serviceType")]
    pub service_type: crate::models::ServiceType,
    /// A list of container.
    #[serde(rename = "containers")]
    pub containers: Vec<crate::models::Container>,
    #[serde(rename = "labelSpecification")]
    pub label_specification: Box<crate::models::LabelSpecification>,
}

impl PurchaseShipmentRequest {
    /// The payload schema for the purchaseShipment operation.
    pub fn new(client_reference_id: String, ship_to: crate::models::Address, ship_from: crate::models::Address, service_type: crate::models::ServiceType, containers: Vec<crate::models::Container>, label_specification: crate::models::LabelSpecification) -> PurchaseShipmentRequest {
        PurchaseShipmentRequest {
            client_reference_id,
            ship_to: Box::new(ship_to),
            ship_from: Box::new(ship_from),
            ship_date: None,
            service_type,
            containers,
            label_specification: Box::new(label_specification),
        }
    }
}


