/*
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RetrieveShippingLabelRequest : The request schema for the retrieveShippingLabel operation.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveShippingLabelRequest {
    #[serde(rename = "labelSpecification")]
    pub label_specification: Box<crate::models::LabelSpecification>,
}

impl RetrieveShippingLabelRequest {
    /// The request schema for the retrieveShippingLabel operation.
    pub fn new(label_specification: crate::models::LabelSpecification) -> RetrieveShippingLabelRequest {
        RetrieveShippingLabelRequest {
            label_specification: Box::new(label_specification),
        }
    }
}


