/*
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ShippingPromiseSet : The promised delivery time and pickup time.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ShippingPromiseSet {
    #[serde(rename = "deliveryWindow", skip_serializing_if = "Option::is_none")]
    pub delivery_window: Option<Box<crate::models::TimeRange>>,
    #[serde(rename = "receiveWindow", skip_serializing_if = "Option::is_none")]
    pub receive_window: Option<Box<crate::models::TimeRange>>,
}

impl ShippingPromiseSet {
    /// The promised delivery time and pickup time.
    pub fn new() -> ShippingPromiseSet {
        ShippingPromiseSet {
            delivery_window: None,
            receive_window: None,
        }
    }
}


