/*
 * Selling Partner API for Shipping
 *
 * Provides programmatic access to Amazon Shipping APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TrackingSummary : The tracking summary.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TrackingSummary {
    /// The derived status based on the events in the eventHistory.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl TrackingSummary {
    /// The tracking summary.
    pub fn new() -> TrackingSummary {
        TrackingSummary {
            status: None,
        }
    }
}


