/*
 * Selling Partner API for Feeds
 *
 * The Selling Partner API for Feeds lets you upload data to Amazon on behalf of a selling partner.
 *
 * The version of the OpenAPI document: 2021-06-30
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateFeedResponse : Response schema.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateFeedResponse {
    /// The identifier for the feed. This identifier is unique only in combination with a seller ID.
    #[serde(rename = "feedId")]
    pub feed_id: String,
}

impl CreateFeedResponse {
    /// Response schema.
    pub fn new(feed_id: String) -> CreateFeedResponse {
        CreateFeedResponse {
            feed_id,
        }
    }
}


