/*
 * Selling Partner API for Feeds
 *
 * The Selling Partner API for Feeds lets you upload data to Amazon on behalf of a selling partner.
 *
 * The version of the OpenAPI document: 2021-06-30
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateFeedDocumentSpecification : Specifies the content type for the createFeedDocument operation.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateFeedDocumentSpecification {
    /// The content type of the feed.
    #[serde(rename = "contentType")]
    pub content_type: String,
}

impl CreateFeedDocumentSpecification {
    /// Specifies the content type for the createFeedDocument operation.
    pub fn new(content_type: String) -> CreateFeedDocumentSpecification {
        CreateFeedDocumentSpecification {
            content_type,
        }
    }
}


