/*
 * Selling Partner API for Feeds
 *
 * The Selling Partner API for Feeds lets you upload data to Amazon on behalf of a selling partner.
 *
 * The version of the OpenAPI document: 2021-06-30
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateFeedDocumentResponse : Information required to upload a feed document's contents.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateFeedDocumentResponse {
    /// The identifier of the feed document.
    #[serde(rename = "feedDocumentId")]
    pub feed_document_id: String,
    /// The presigned URL for uploading the feed contents. This URL expires after 5 minutes.
    #[serde(rename = "url")]
    pub url: String,
}

impl CreateFeedDocumentResponse {
    /// Information required to upload a feed document's contents.
    pub fn new(feed_document_id: String, url: String) -> CreateFeedDocumentResponse {
        CreateFeedDocumentResponse {
            feed_document_id,
            url,
        }
    }
}


