/*
 * Selling Partner API for Feeds
 *
 * The Selling Partner API for Feeds lets you upload data to Amazon on behalf of a selling partner.
 *
 * The version of the OpenAPI document: 2021-06-30
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetFeedsResponse : Response schema.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetFeedsResponse {
    /// A list of feeds.
    #[serde(rename = "feeds")]
    pub feeds: Vec<crate::models::Feed>,
    /// Returned when the number of results exceeds pageSize. To get the next page of results, call the getFeeds operation with this token as the only parameter.
    #[serde(rename = "nextToken", skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
}

impl GetFeedsResponse {
    /// Response schema.
    pub fn new(feeds: Vec<crate::models::Feed>) -> GetFeedsResponse {
        GetFeedsResponse {
            feeds,
            next_token: None,
        }
    }
}


