/*
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DebtRecoveryItem : An item of a debt payment or debt adjustment.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DebtRecoveryItem {
    #[serde(rename = "RecoveryAmount", skip_serializing_if = "Option::is_none")]
    pub recovery_amount: Option<Box<crate::models::Currency>>,
    #[serde(rename = "OriginalAmount", skip_serializing_if = "Option::is_none")]
    pub original_amount: Option<Box<crate::models::Currency>>,
    #[serde(rename = "GroupBeginDate", skip_serializing_if = "Option::is_none")]
    pub group_begin_date: Option<String>,
    #[serde(rename = "GroupEndDate", skip_serializing_if = "Option::is_none")]
    pub group_end_date: Option<String>,
}

impl DebtRecoveryItem {
    /// An item of a debt payment or debt adjustment.
    pub fn new() -> DebtRecoveryItem {
        DebtRecoveryItem {
            recovery_amount: None,
            original_amount: None,
            group_begin_date: None,
            group_end_date: None,
        }
    }
}


