/*
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RemovalShipmentAdjustmentEvent : A financial adjustment event for FBA liquidated inventory. A positive value indicates money owed to Amazon by the buyer (for example, when the charge was incorrectly calculated as less than it should be). A negative value indicates a full or partial refund owed to the buyer (for example, when the buyer receives damaged items or fewer items than ordered).



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RemovalShipmentAdjustmentEvent {
    #[serde(rename = "PostedDate", skip_serializing_if = "Option::is_none")]
    pub posted_date: Option<String>,
    /// The unique identifier for the adjustment event.
    #[serde(rename = "AdjustmentEventId", skip_serializing_if = "Option::is_none")]
    pub adjustment_event_id: Option<String>,
    /// The merchant removal orderId.
    #[serde(rename = "MerchantOrderId", skip_serializing_if = "Option::is_none")]
    pub merchant_order_id: Option<String>,
    /// The orderId for shipping inventory.
    #[serde(rename = "OrderId", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<String>,
    /// The type of removal order.  Possible values:  * WHOLESALE_LIQUIDATION.
    #[serde(rename = "TransactionType", skip_serializing_if = "Option::is_none")]
    pub transaction_type: Option<String>,
    /// A comma-delimited list of Removal shipmentItemAdjustment details for FBA inventory.
    #[serde(rename = "RemovalShipmentItemAdjustmentList", skip_serializing_if = "Option::is_none")]
    pub removal_shipment_item_adjustment_list: Option<Vec<crate::models::RemovalShipmentItemAdjustment>>,
}

impl RemovalShipmentAdjustmentEvent {
    /// A financial adjustment event for FBA liquidated inventory. A positive value indicates money owed to Amazon by the buyer (for example, when the charge was incorrectly calculated as less than it should be). A negative value indicates a full or partial refund owed to the buyer (for example, when the buyer receives damaged items or fewer items than ordered).
    pub fn new() -> RemovalShipmentAdjustmentEvent {
        RemovalShipmentAdjustmentEvent {
            posted_date: None,
            adjustment_event_id: None,
            merchant_order_id: None,
            order_id: None,
            transaction_type: None,
            removal_shipment_item_adjustment_list: None,
        }
    }
}


