/*
 * Selling Partner API for Listings Items
 *
 * The Selling Partner API for Listings Items (Listings Items API) provides programmatic access to selling partner listings on Amazon. Use this API in collaboration with the Selling Partner API for Product Type Definitions, which you use to retrieve the information about Amazon product types needed to use the Listings Items API.  For more information, see the [Listings Items API Use Case Guide](doc:listings-items-api-v2021-08-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2021-08-01
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FulfillmentAvailability : Fulfillment availability details for the listings item.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FulfillmentAvailability {
    /// Designates which fulfillment network will be used.
    #[serde(rename = "fulfillmentChannelCode")]
    pub fulfillment_channel_code: String,
    /// The quantity of the item you are making available for sale.
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<i32>,
}

impl FulfillmentAvailability {
    /// Fulfillment availability details for the listings item.
    pub fn new(fulfillment_channel_code: String) -> FulfillmentAvailability {
        FulfillmentAvailability {
            fulfillment_channel_code,
            quantity: None,
        }
    }
}


