/*
 * Selling Partner API for Listings Items
 *
 * The Selling Partner API for Listings Items (Listings Items API) provides programmatic access to selling partner listings on Amazon. Use this API in collaboration with the Selling Partner API for Product Type Definitions, which you use to retrieve the information about Amazon product types needed to use the Listings Items API.  For more information, see the [Listings Items API Use Case Guide](doc:listings-items-api-v2021-08-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2021-08-01
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ItemImage : Image for the listings item.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ItemImage {
    /// Link, or URL, for the image.
    #[serde(rename = "link")]
    pub link: String,
    /// Height of the image in pixels.
    #[serde(rename = "height")]
    pub height: i32,
    /// Width of the image in pixels.
    #[serde(rename = "width")]
    pub width: i32,
}

impl ItemImage {
    /// Image for the listings item.
    pub fn new(link: String, height: i32, width: i32) -> ItemImage {
        ItemImage {
            link,
            height,
            width,
        }
    }
}


