/*
 * Selling Partner API for Listings Items
 *
 * The Selling Partner API for Listings Items (Listings Items API) provides programmatic access to selling partner listings on Amazon. Use this API in collaboration with the Selling Partner API for Product Type Definitions, which you use to retrieve the information about Amazon product types needed to use the Listings Items API.  For more information, see the [Listings Items API Use Case Guide](doc:listings-items-api-v2021-08-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2021-08-01
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Item : A listings item.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Item {
    /// A selling partner provided identifier for an Amazon listing.
    #[serde(rename = "sku")]
    pub sku: String,
    /// Summary details of a listings item.
    #[serde(rename = "summaries", skip_serializing_if = "Option::is_none")]
    pub summaries: Option<Vec<crate::models::ItemSummaryByMarketplace>>,
    /// JSON object containing structured listings item attribute data keyed by attribute name.
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<serde_json::Value>,
    /// Issues associated with the listings item.
    #[serde(rename = "issues", skip_serializing_if = "Option::is_none")]
    pub issues: Option<Vec<crate::models::Issue>>,
    /// Offer details for the listings item.
    #[serde(rename = "offers", skip_serializing_if = "Option::is_none")]
    pub offers: Option<Vec<crate::models::ItemOfferByMarketplace>>,
    /// Fulfillment availability for the listings item.
    #[serde(rename = "fulfillmentAvailability", skip_serializing_if = "Option::is_none")]
    pub fulfillment_availability: Option<Vec<crate::models::FulfillmentAvailability>>,
    #[serde(rename = "procurement", skip_serializing_if = "Option::is_none")]
    pub procurement: Option<Box<crate::models::ItemProcurement>>,
}

impl Item {
    /// A listings item.
    pub fn new(sku: String) -> Item {
        Item {
            sku,
            summaries: None,
            attributes: None,
            issues: None,
            offers: None,
            fulfillment_availability: None,
            procurement: None,
        }
    }
}


