/*
 * Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data
 *
 * The Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data provides programmatic access to vendor direct fulfillment sandbox test data.
 *
 * The version of the OpenAPI document: 2021-10-28
 * 
 * Generated by: https://openapi-generator.tech
 */

/// OrderScenarioRequest : The party identifiers required to generate the test data.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrderScenarioRequest {
    #[serde(rename = "sellingParty")]
    pub selling_party: Box<crate::models::PartyIdentification>,
    #[serde(rename = "shipFromParty")]
    pub ship_from_party: Box<crate::models::PartyIdentification>,
}

impl OrderScenarioRequest {
    /// The party identifiers required to generate the test data.
    pub fn new(selling_party: crate::models::PartyIdentification, ship_from_party: crate::models::PartyIdentification) -> OrderScenarioRequest {
        OrderScenarioRequest {
            selling_party: Box::new(selling_party),
            ship_from_party: Box::new(ship_from_party),
        }
    }
}


