/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetOffersHttpStatusLine : The HTTP status line associated with the response.  For more information, consult [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html).



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetOffersHttpStatusLine {
    /// The HTTP response Status Code.
    #[serde(rename = "statusCode", skip_serializing_if = "Option::is_none")]
    pub status_code: Option<i32>,
    /// The HTTP response Reason-Phase.
    #[serde(rename = "reasonPhrase", skip_serializing_if = "Option::is_none")]
    pub reason_phrase: Option<String>,
}

impl GetOffersHttpStatusLine {
    /// The HTTP status line associated with the response.  For more information, consult [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html).
    pub fn new() -> GetOffersHttpStatusLine {
        GetOffersHttpStatusLine {
            status_code: None,
            reason_phrase: None,
        }
    }
}


