/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// HttpResponseHeaders : A mapping of additional HTTP headers to send/receive for the individual batch request.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HttpResponseHeaders {
    /// The timestamp that the API request was received.  For more information, consult [RFC 2616 Section 14](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html).
    #[serde(rename = "Date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// Unique request reference ID.
    #[serde(rename = "x-amzn-RequestId", skip_serializing_if = "Option::is_none")]
    pub x_amzn_request_id: Option<String>,
}

impl HttpResponseHeaders {
    /// A mapping of additional HTTP headers to send/receive for the individual batch request.
    pub fn new() -> HttpResponseHeaders {
        HttpResponseHeaders {
            date: None,
            x_amzn_request_id: None,
        }
    }
}


