/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ItemOffersRequestParams {
    /// A marketplace identifier. Specifies the marketplace for which prices are returned.
    #[serde(rename = "MarketplaceId")]
    pub marketplace_id: String,
    #[serde(rename = "ItemCondition")]
    pub item_condition: crate::models::ItemCondition,
    #[serde(rename = "CustomerType", skip_serializing_if = "Option::is_none")]
    pub customer_type: Option<crate::models::CustomerType>,
    /// The Amazon Standard Identification Number (ASIN) of the item. This is the same Asin passed as a request parameter.
    #[serde(rename = "Asin", skip_serializing_if = "Option::is_none")]
    pub asin: Option<String>,
}

impl ItemOffersRequestParams {
    pub fn new(marketplace_id: String, item_condition: crate::models::ItemCondition) -> ItemOffersRequestParams {
        ItemOffersRequestParams {
            marketplace_id,
            item_condition,
            customer_type: None,
            asin: None,
        }
    }
}


