/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ItemOffersRequestParamsAllOf {
    /// The Amazon Standard Identification Number (ASIN) of the item. This is the same Asin passed as a request parameter.
    #[serde(rename = "Asin", skip_serializing_if = "Option::is_none")]
    pub asin: Option<String>,
}

impl ItemOffersRequestParamsAllOf {
    pub fn new() -> ItemOffersRequestParamsAllOf {
        ItemOffersRequestParamsAllOf {
            asin: None,
        }
    }
}


