/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Points {
    /// The number of points.
    #[serde(rename = "PointsNumber", skip_serializing_if = "Option::is_none")]
    pub points_number: Option<i32>,
    #[serde(rename = "PointsMonetaryValue", skip_serializing_if = "Option::is_none")]
    pub points_monetary_value: Option<Box<crate::models::MoneyType>>,
}

impl Points {
    pub fn new() -> Points {
        Points {
            points_number: None,
            points_monetary_value: None,
        }
    }
}


