/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateReturnItem : An item that Amazon accepted for return.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateReturnItem {
    /// An identifier assigned by the seller to the return item.
    #[serde(rename = "sellerReturnItemId")]
    pub seller_return_item_id: String,
    /// The identifier assigned to the item by the seller when the fulfillment order was created.
    #[serde(rename = "sellerFulfillmentOrderItemId")]
    pub seller_fulfillment_order_item_id: String,
    /// The identifier for the shipment that is associated with the return item.
    #[serde(rename = "amazonShipmentId")]
    pub amazon_shipment_id: String,
    /// The return reason code assigned to the return item by the seller.
    #[serde(rename = "returnReasonCode")]
    pub return_reason_code: String,
    /// An optional comment about the return item.
    #[serde(rename = "returnComment", skip_serializing_if = "Option::is_none")]
    pub return_comment: Option<String>,
}

impl CreateReturnItem {
    /// An item that Amazon accepted for return.
    pub fn new(seller_return_item_id: String, seller_fulfillment_order_item_id: String, amazon_shipment_id: String, return_reason_code: String) -> CreateReturnItem {
        CreateReturnItem {
            seller_return_item_id,
            seller_fulfillment_order_item_id,
            amazon_shipment_id,
            return_reason_code,
            return_comment: None,
        }
    }
}


