/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DeliveryWindow : The time range within which a Scheduled Delivery fulfillment order should be delivered.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeliveryWindow {
    #[serde(rename = "startDate")]
    pub start_date: String,
    #[serde(rename = "endDate")]
    pub end_date: String,
}

impl DeliveryWindow {
    /// The time range within which a Scheduled Delivery fulfillment order should be delivered.
    pub fn new(start_date: String, end_date: String) -> DeliveryWindow {
        DeliveryWindow {
            start_date,
            end_date,
        }
    }
}


