/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FulfillmentPolicy : The FulfillmentPolicy value specified when you submitted the createFulfillmentOrder operation.

/// The FulfillmentPolicy value specified when you submitted the createFulfillmentOrder operation.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FulfillmentPolicy {
    #[serde(rename = "FillOrKill")]
    FillOrKill,
    #[serde(rename = "FillAll")]
    FillAll,
    #[serde(rename = "FillAllAvailable")]
    FillAllAvailable,

}

impl ToString for FulfillmentPolicy {
    fn to_string(&self) -> String {
        match self {
            Self::FillOrKill => String::from("FillOrKill"),
            Self::FillAll => String::from("FillAll"),
            Self::FillAllAvailable => String::from("FillAllAvailable"),
        }
    }
}

impl Default for FulfillmentPolicy {
    fn default() -> FulfillmentPolicy {
        Self::FillOrKill
    }
}




