/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 * Generated by: https://openapi-generator.tech
 */

/// GetFulfillmentPreviewItem : Item information for a fulfillment order preview.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetFulfillmentPreviewItem {
    /// The seller SKU of the item.
    #[serde(rename = "sellerSku")]
    pub seller_sku: String,
    /// The item quantity.
    #[serde(rename = "quantity")]
    pub quantity: i32,
    #[serde(rename = "perUnitDeclaredValue", skip_serializing_if = "Option::is_none")]
    pub per_unit_declared_value: Option<Box<crate::models::Money>>,
    /// A fulfillment order item identifier that the seller creates to track items in the fulfillment preview.
    #[serde(rename = "sellerFulfillmentOrderItemId")]
    pub seller_fulfillment_order_item_id: String,
}

impl GetFulfillmentPreviewItem {
    /// Item information for a fulfillment order preview.
    pub fn new(seller_sku: String, quantity: i32, seller_fulfillment_order_item_id: String) -> GetFulfillmentPreviewItem {
        GetFulfillmentPreviewItem {
            seller_sku,
            quantity,
            per_unit_declared_value: None,
            seller_fulfillment_order_item_id,
        }
    }
}


